### ISSUE TITLE
KeyError: 'defaultnamingcontext'

### ISSUE THREAD

**Issue by cosad3s** [franc-pentest/ldeep#19]
Hello,

I am using ldeep with LDAP service, and an error happens:

```bash
❯ ldeep ldap -a -d "DOMAIN" -s ldap://X.X.X.X all output
Traceback (most recent call last):
  File "/usr/local/bin/ldeep", line 33, in <module>
    sys.exit(load_entry_point('ldeep==1.0.12', 'console_scripts', 'ldeep')())
  File "/usr/local/lib/python3.10/dist-packages/ldeep-1.0.12-py3.10.egg/ldeep/__main__.py", line 832, in main
  File "/usr/local/lib/python3.10/dist-packages/ldeep-1.0.12-py3.10.egg/ldeep/views/ldap_activedirectory.py", line 267, in __init__
  File "/usr/lib/python3/dist-packages/ldap3/utils/ciDict.py", line 68, in __getitem__
    return self._store[self._case_insensitive_keymap[self._ci_key(key)]]
KeyError: 'defaultnamingcontext'
```

I think this is because there is no "defaultnamingcontext" exposed from my tested service.

**Comment by flgy** [comment]
Ldeep's main goal is to interact with Active Directory LDAP. Unfortunately, as for now, we don't plan to make ldeep working with other kind of LDAP service.
