### ISSUE TITLE
No such file or directory ldeep/../VERSION

### ISSUE THREAD

**Issue by 3ldidi94** [franc-pentest/ldeep#77]
Hello,

I get an error after a fresh installation of ldeep about the VERSION file that is missing in the `/home/user/.local/lib/python3.11/site-packages/ldeep/../VERSION`. 

The Python error says that it is in the `__init__` file :

```
Traceback (most recent call last):
  File "/home/user/.local/bin/ldeep", line 5, in <module>
    from ldeep.__main__ import main
  File "/home/user/.local/lib/python3.11/site-packages/ldeep/__init__.py", line 3, in <module>
    __version__ = open(os.path.join(os.path.dirname(__file__), "../VERSION")).read().strip()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/lib/python3.11/site-packages/ldeep/../VERSION'

```

Ldeep seems to work after a manual copy of this file to the specified location

**Comment by QU35T-code** [comment]
Same issue

```bash
pipx install --system-site-packages ldeep --force

ldeep --help
Traceback (most recent call last):
  File "/root/.local/bin/ldeep", line 5, in <module>
    from ldeep.__main__ import main
  File "/root/.local/share/pipx/venvs/ldeep/lib/python3.11/site-packages/ldeep/__init__.py", line 3, in <module>
    __version__ = open(os.path.join(os.path.dirname(__file__), "../VERSION")).read().strip()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/pipx/venvs/ldeep/lib/python3.11/site-packages/ldeep/../VERSION'
```

_Catched by the Exegol pipeline_
