### ISSUE TITLE
Error importing TLS_CHANNEL_BINDING from ldap3

### ISSUE THREAD

**Issue by 3ldidi94** [franc-pentest/ldeep#91]
Hello,

Using the last binary I get the following error message regarding the TLS_CHANNEL_BINDING module in the ldap3 lib.

```
Traceback (most recent call last):
  File "/tmp/onefile_847008_1720789016_268097/__main__.py", line 27, in <module>
  File "/tmp/onefile_847008_1720789016_268097/ldeep/views/ldap_activedirectory.py", line 10, in <module ldeep.views.ldap_activedirectory>
ImportError: cannot import name 'TLS_CHANNEL_BINDING' from 'ldap3' (/tmp/onefile_847008_1720789016_268097/ldap3/__init__.py)
```

I tried to install the last available version 2.9.1 of the python3-ldap3 lib and there is no module called TLS_CHANNEL_BINDING.

I don't have this error when installing with `python -m pip install git+https://github.com/franc-pentest/ldeep`

**Comment by tiyeuse** [comment]
It's because ldap3 python library latest release is 2.9.1, which was released on Jul 17, 2021. Many improvements on that library have been added on the github repository and no additional release have been made.
If you do `pip install git+https://github.com/franc-pentest/ldeep`, it will pull a specific version of the ldap3 library with the new features, including the channel binding one.
I suggest you to keep installing ldeep using the github repo: `python -m pip install git+https://github.com/franc-pentest/ldeep`.

**Comment by BastienFaure** [comment]
I will check if we can have a workaround. It shouldn't be an issue to include that in the final binary.

**Comment by laxa** [comment]
Hello, I cannot reproduce this issue with the up-to-date repository, closing this issue.

If you encounter the issue again, please provide maximum details.
